packages:
  - api
  - bot
  - worker
  - ml
  - packages/shared
  - apps/agent
  - prisma
  - utils

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - esbuild
  - msgpackr-extract
  - prisma
